In [2]:
import numpy as np
a=np.array([1,2,3,4])
print(a)
print(type(a))
print(a.ndim)

[1 2 3 4]
<class 'numpy.ndarray'>
1


In [3]:
ar3=np.array([[[1,2,3,4,5],[6,7,8,9,0]]])
print(ar3)
print(ar3.ndim)

[[[1 2 3 4 5]
  [6 7 8 9 0]]]
3


In [4]:
print(ar3.shape)

(1, 2, 5)


In [5]:
print(ar3.size)

10


In [6]:
print(ar3.itemsize)

4


In [7]:
print(ar3.dtype)

int32


In [29]:
ar4=np.arange(0,10).reshape(1,2,5)
print(ar4)

[[[0 1 2 3 4]
  [5 6 7 8 9]]]


In [79]:
ar5=np.arange(64).reshape(4,4,4)
print(ar5)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]
  [12 13 14 15]]

 [[16 17 18 19]
  [20 21 22 23]
  [24 25 26 27]
  [28 29 30 31]]

 [[32 33 34 35]
  [36 37 38 39]
  [40 41 42 43]
  [44 45 46 47]]

 [[48 49 50 51]
  [52 53 54 55]
  [56 57 58 59]
  [60 61 62 63]]]


In [32]:
ar6=np.arange(0,6).reshape(1,3,2)
print(ar6)


[[[0 1]
  [2 3]
  [4 5]]]


In [64]:
var=np.random.seed(0)

var=np.random.randint(0,1000,(5,5))
print(var)
print(var[0:2])

[[684 559 629 192 835]
 [763 707 359   9 723]
 [277 754 804 599  70]
 [472 600 396 314 705]
 [486 551  87 174 600]]
[[684 559 629 192 835]
 [763 707 359   9 723]]


In [74]:
print(var[0:2,0:2])

[[684 559]
 [763 707]]


In [77]:
l=[]
for i in range(1,5):
    s=int(input("Enter element"))
    l.append(s)
print(l)
print(np.array(l))
    

Enter element10
Enter element20
Enter element30
Enter element40
[10, 20, 30, 40]
[10 20 30 40]


In [84]:
g3d=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(g3d)
for i,j in np.ndenumerate(g3d):
    print(i,j)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(0, 0) 1
(0, 1) 2
(0, 2) 3
(1, 0) 4
(1, 1) 5
(1, 2) 6
(2, 0) 7
(2, 1) 8
(2, 2) 9


In [107]:
a_0=np.zeros([3,3],dtype=int)
print(a_0)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [106]:
a_1=np.ones([3,3],dtype=int)
print(a_1)

[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [90]:
a_2=np.full([3,3],12)
print(a_2)

[[12 12 12]
 [12 12 12]
 [12 12 12]]


In [99]:
import numpy as np
block_1 = np.array([[0, 0], [0, 0]])
block_2 = np.array([[1, 0], [0, 1]])
block_3 = np.array([[0, 0, 0, 0]])
top_row = np.hstack((block_1, block_2))
block_new = np.vstack((top_row, block_3))
print(block_new)


[[0 0 1 0]
 [0 0 0 1]
 [0 0 0 0]]


In [105]:
import numpy as np

output_matrix = np.eye(3)

print(output_matrix)
output_matrix = np.eye(3, dtype=int)

print(output_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1 0 0]
 [0 1 0]
 [0 0 1]]


In [1]:
day 2

SyntaxError: invalid syntax (1584776874.py, line 1)

In [7]:
import numpy as np
ar9=np.array([[1,2,3],[4,5,6]])
print(ar9)

[[1 2 3]
 [4 5 6]]


In [8]:
ab=np.ones_like(ar9)
print(ab)

[[1 1 1]
 [1 1 1]]


In [14]:
s_1=np.array([[1,2,3],[4,5,6]])
s_2=np.array([[1,2,3],[4,5,6]])
ans=np.concatenate((s_1,s_2))
print(ans)

[[1 2 3]
 [4 5 6]
 [1 2 3]
 [4 5 6]]


In [15]:
s_1=np.array([[1,2,3],[4,5,6]])
s_2=np.array([[1,2,3],[4,5,6]])
ans=np.concatenate((s_1,s_2),axis=1)
print(ans)

[[1 2 3 1 2 3]
 [4 5 6 4 5 6]]


In [26]:
s_1=np.array([[1,2,3,4,5,6]])
s_2=np.array_split(s_2,2)
print(s_2)

[array([[[1, 2, 3]]]), array([[[4, 5, 6]]])]


In [24]:
import numpy as np
block_1 = np.array([[1, 2], [3, 4]])
block_2 = np.array([[5, 6], [7, 8]])
block_3 = np.array([[0, 0, 0, 0]])
top_row = np.hstack((block_1, block_2))
block_new = np.vstack((top_row, block_3))
print(block_new)


[[1 2 5 6]
 [3 4 7 8]
 [0 0 0 0]]


In [5]:
import pandas as pd
df=pd.read_csv('C:/Users/Welcome/Downloads/archive (3)/CarPrice_Assignment.csv')
df

car_ID  symboling                   CarName fueltype aspiration  \
0         1          3        alfa-romero giulia      gas        std   
1         2          3       alfa-romero stelvio      gas        std   
2         3          1  alfa-romero Quadrifoglio      gas        std   
3         4          2               audi 100 ls      gas        std   
4         5          2                audi 100ls      gas        std   
..      ...        ...                       ...      ...        ...   
200     201         -1           volvo 145e (sw)      gas        std   
201     202         -1               volvo 144ea      gas      turbo   
202     203         -1               volvo 244dl      gas        std   
203     204         -1                 volvo 246   diesel      turbo   
204     205         -1               volvo 264gl      gas      turbo   

    doornumber      carbody drivewheel enginelocation  wheelbase  ...  \
0          two  convertible        rwd          front       88.6  ...   
1          two  convertible        rwd          front       88.6  ...   
2          two    hatchback        rwd          front       94.5  ...   
3         four        sedan        fwd          front       99.8  ...   
4         four        sedan        4wd          front       99.4  ...   
..         ...          ...        ...            ...        ...  ...   
200       four        sedan        rwd          front      109.1  ...   
201       four        sedan        rwd          front      109.1  ...   
202       four        sedan        rwd          front      109.1  ...   
203       four        sedan        rwd          front      109.1  ...   
204       four        sedan        rwd          front      109.1  ...   

     enginesize  fuelsystem  boreratio  stroke compressionratio horsepower  \
0           130        mpfi       3.47    2.68              9.0        111   
1           130        mpfi       3.47    2.68              9.0        111   
2           152        mpfi       2.68    3.47              9.0        154   
3           109        mpfi       3.19    3.40             10.0        102   
4           136        mpfi       3.19    3.40              8.0        115   
..          ...         ...        ...     ...              ...        ...   
200         141        mpfi       3.78    3.15              9.5        114   
201         141        mpfi       3.78    3.15              8.7        160   
202         173        mpfi       3.58    2.87              8.8        134   
203         145         idi       3.01    3.40             23.0        106   
204         141        mpfi       3.78    3.15              9.5        114   

     peakrpm citympg  highwaympg    price  
0       5000      21          27  13495.0  
1       5000      21          27  16500.0  
2       5000      19          26  16500.0  
3       5500      24          30  13950.0  
4       5500      18          22  17450.0  
..       ...     ...         ...      ...  
200     5400      23          28  16845.0  
201     5300      19          25  19045.0  
202     5500      18          23  21485.0  
203     4800      26          27  22470.0  
204     5400      19          25  22625.0  

[205 rows x 26 columns]

In [29]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 205 entries, 0 to 204
Data columns (total 26 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   car_ID            205 non-null    int64  
 1   symboling         205 non-null    int64  
 2   CarName           205 non-null    object 
 3   fueltype          205 non-null    object 
 4   aspiration        205 non-null    object 
 5   doornumber        205 non-null    object 
 6   carbody           205 non-null    object 
 7   drivewheel        205 non-null    object 
 8   enginelocation    205 non-null    object 
 9   wheelbase         205 non-null    float64
 10  carlength         205 non-null    float64
 11  carwidth          205 non-null    float64
 12  carheight         205 non-null    float64
 13  curbweight        205 non-null    int64  
 14  enginetype        205 non-null    object 
 15  cylindernumber    205 non-null    object 
 16  enginesize        205 non-null    int64  
 1

In [30]:
df.head()

car_ID  symboling                   CarName fueltype aspiration doornumber  \
0       1          3        alfa-romero giulia      gas        std        two   
1       2          3       alfa-romero stelvio      gas        std        two   
2       3          1  alfa-romero Quadrifoglio      gas        std        two   
3       4          2               audi 100 ls      gas        std       four   
4       5          2                audi 100ls      gas        std       four   

       carbody drivewheel enginelocation  wheelbase  ...  enginesize  \
0  convertible        rwd          front       88.6  ...         130   
1  convertible        rwd          front       88.6  ...         130   
2    hatchback        rwd          front       94.5  ...         152   
3        sedan        fwd          front       99.8  ...         109   
4        sedan        4wd          front       99.4  ...         136   

   fuelsystem  boreratio  stroke compressionratio horsepower  peakrpm citympg  \
0        mpfi       3.47    2.68              9.0        111     5000      21   
1        mpfi       3.47    2.68              9.0        111     5000      21   
2        mpfi       2.68    3.47              9.0        154     5000      19   
3        mpfi       3.19    3.40             10.0        102     5500      24   
4        mpfi       3.19    3.40              8.0        115     5500      18   

   highwaympg    price  
0          27  13495.0  
1          27  16500.0  
2          26  16500.0  
3          30  13950.0  
4          22  17450.0  

[5 rows x 26 columns]

In [31]:
df.tail()

car_ID  symboling          CarName fueltype aspiration doornumber  \
200     201         -1  volvo 145e (sw)      gas        std       four   
201     202         -1      volvo 144ea      gas      turbo       four   
202     203         -1      volvo 244dl      gas        std       four   
203     204         -1        volvo 246   diesel      turbo       four   
204     205         -1      volvo 264gl      gas      turbo       four   

    carbody drivewheel enginelocation  wheelbase  ...  enginesize  fuelsystem  \
200   sedan        rwd          front      109.1  ...         141        mpfi   
201   sedan        rwd          front      109.1  ...         141        mpfi   
202   sedan        rwd          front      109.1  ...         173        mpfi   
203   sedan        rwd          front      109.1  ...         145         idi   
204   sedan        rwd          front      109.1  ...         141        mpfi   

     boreratio  stroke compressionratio horsepower  peakrpm citympg  \
200       3.78    3.15              9.5        114     5400      23   
201       3.78    3.15              8.7        160     5300      19   
202       3.58    2.87              8.8        134     5500      18   
203       3.01    3.40             23.0        106     4800      26   
204       3.78    3.15              9.5        114     5400      19   

     highwaympg    price  
200          28  16845.0  
201          25  19045.0  
202          23  21485.0  
203          27  22470.0  
204          25  22625.0  

[5 rows x 26 columns]

In [32]:
df.describe()

car_ID   symboling   wheelbase   carlength    carwidth   carheight  \
count  205.000000  205.000000  205.000000  205.000000  205.000000  205.000000   
mean   103.000000    0.834146   98.756585  174.049268   65.907805   53.724878   
std     59.322565    1.245307    6.021776   12.337289    2.145204    2.443522   
min      1.000000   -2.000000   86.600000  141.100000   60.300000   47.800000   
25%     52.000000    0.000000   94.500000  166.300000   64.100000   52.000000   
50%    103.000000    1.000000   97.000000  173.200000   65.500000   54.100000   
75%    154.000000    2.000000  102.400000  183.100000   66.900000   55.500000   
max    205.000000    3.000000  120.900000  208.100000   72.300000   59.800000   

        curbweight  enginesize   boreratio      stroke  compressionratio  \
count   205.000000  205.000000  205.000000  205.000000        205.000000   
mean   2555.565854  126.907317    3.329756    3.255415         10.142537   
std     520.680204   41.642693    0.270844    0.313597          3.972040   
min    1488.000000   61.000000    2.540000    2.070000          7.000000   
25%    2145.000000   97.000000    3.150000    3.110000          8.600000   
50%    2414.000000  120.000000    3.310000    3.290000          9.000000   
75%    2935.000000  141.000000    3.580000    3.410000          9.400000   
max    4066.000000  326.000000    3.940000    4.170000         23.000000   

       horsepower      peakrpm     citympg  highwaympg         price  
count  205.000000   205.000000  205.000000  205.000000    205.000000  
mean   104.117073  5125.121951   25.219512   30.751220  13276.710571  
std     39.544167   476.985643    6.542142    6.886443   7988.852332  
min     48.000000  4150.000000   13.000000   16.000000   5118.000000  
25%     70.000000  4800.000000   19.000000   25.000000   7788.000000  
50%     95.000000  5200.000000   24.000000   30.000000  10295.000000  
75%    116.000000  5500.000000   30.000000   34.000000  16503.000000  
max    288.000000  6600.000000   49.000000   54.000000  45400.000000

In [33]:
df.isnull(
)

car_ID  symboling  CarName  fueltype  aspiration  doornumber  carbody  \
0     False      False    False     False       False       False    False   
1     False      False    False     False       False       False    False   
2     False      False    False     False       False       False    False   
3     False      False    False     False       False       False    False   
4     False      False    False     False       False       False    False   
..      ...        ...      ...       ...         ...         ...      ...   
200   False      False    False     False       False       False    False   
201   False      False    False     False       False       False    False   
202   False      False    False     False       False       False    False   
203   False      False    False     False       False       False    False   
204   False      False    False     False       False       False    False   

     drivewheel  enginelocation  wheelbase  ...  enginesize  fuelsystem  \
0         False           False      False  ...       False       False   
1         False           False      False  ...       False       False   
2         False           False      False  ...       False       False   
3         False           False      False  ...       False       False   
4         False           False      False  ...       False       False   
..          ...             ...        ...  ...         ...         ...   
200       False           False      False  ...       False       False   
201       False           False      False  ...       False       False   
202       False           False      False  ...       False       False   
203       False           False      False  ...       False       False   
204       False           False      False  ...       False       False   

     boreratio  stroke  compressionratio  horsepower  peakrpm  citympg  \
0        False   False             False       False    False    False   
1        False   False             False       False    False    False   
2        False   False             False       False    False    False   
3        False   False             False       False    False    False   
4        False   False             False       False    False    False   
..         ...     ...               ...         ...      ...      ...   
200      False   False             False       False    False    False   
201      False   False             False       False    False    False   
202      False   False             False       False    False    False   
203      False   False             False       False    False    False   
204      False   False             False       False    False    False   

     highwaympg  price  
0         False  False  
1         False  False  
2         False  False  
3         False  False  
4         False  False  
..          ...    ...  
200       False  False  
201       False  False  
202       False  False  
203       False  False  
204       False  False  

[205 rows x 26 columns]

In [34]:
df.isnull().sum()

car_ID              0
symboling           0
CarName             0
fueltype            0
aspiration          0
doornumber          0
carbody             0
drivewheel          0
enginelocation      0
wheelbase           0
carlength           0
carwidth            0
carheight           0
curbweight          0
enginetype          0
cylindernumber      0
enginesize          0
fuelsystem          0
boreratio           0
stroke              0
compressionratio    0
horsepower          0
peakrpm             0
citympg             0
highwaympg          0
price               0
dtype: int64

In [66]:
df.drop_duplicates

<bound method DataFrame.drop_duplicates of      car_ID  symboling                   CarName fueltype aspiration  \
0         1          3        alfa-romero giulia      gas        std   
1         2          3       alfa-romero stelvio      gas        std   
2         3          1  alfa-romero Quadrifoglio      gas        std   
3         4          2               audi 100 ls      gas        std   
4         5          2                audi 100ls      gas        std   
..      ...        ...                       ...      ...        ...   
200     201         -1           volvo 145e (sw)      gas        std   
201     202         -1               volvo 144ea      gas      turbo   
202     203         -1               volvo 244dl      gas        std   
203     204         -1                 volvo 246   diesel      turbo   
204     205         -1               volvo 264gl      gas      turbo   

    doornumber      carbody drivewheel enginelocation  wheelbase  ...  \
0          two  con

In [40]:
df.describe(include='O')

CarName fueltype aspiration doornumber carbody drivewheel  \
count             205      205        205        205     205        205   
unique            147        2          2          2       5          3   
top     toyota corona      gas        std       four   sedan        fwd   
freq                6      185        168        115      96        120   

       enginelocation enginetype cylindernumber fuelsystem  
count             205        205            205        205  
unique              2          7              7          8  
top             front        ohc           four       mpfi  
freq              202        148            159         94

In [64]:
kn=df.sample(frac=0.2)
kn

car_ID  symboling                    CarName fueltype aspiration  \
164     165          1              toyota corona      gas        std   
26       27          1            dodge colt (sw)      gas        std   
188     189          2          volkswagen dasher      gas        std   
142     143          0                 subaru brz      gas        std   
165     166          1  toyota celica gt liftback      gas        std   
186     187          2        volkswagen 411 (sw)      gas        std   
82       83          3       mitsubishi outlander      gas      turbo   
196     197         -2                volvo 244dl      gas        std   
144     145          0                  subaru r1      gas        std   
195     196         -1                volvo 144ea      gas        std   
50       51          1                  maxda rx3      gas        std   
42       43          1         honda civic (auto)      gas        std   
73       74          0      buick century special      gas        std   
105     106          3               nissan kicks      gas      turbo   
67       68         -1   buick electra 225 custom   diesel      turbo   
160     161          0              toyota corona      gas        std   
5         6          2                   audi fox      gas        std   
60       61          0         mazda glc custom l      gas        std   
151     152          1              toyota corona      gas        std   
172     173          2            toyota cressida      gas        std   
189     190          3                  vw dasher      gas        std   
85       86          1         mitsubishi montero      gas        std   
44       45          1               isuzu D-Max       gas        std   
204     205         -1                volvo 264gl      gas      turbo   
125     126          3              porsche macan      gas        std   
200     201         -1            volvo 145e (sw)      gas        std   
203     204         -1                  volvo 246   diesel      turbo   
202     203         -1                volvo 244dl      gas        std   
38       39          0           honda civic 1300      gas        std   
11       12          0                   bmw 320i      gas        std   
180     181         -1             toyota starlet      gas        std   
185     186          2          volkswagen type 3      gas        std   
36       37          0        honda civic 1500 gl      gas        std   
162     163          0             toyota mark ii      gas        std   
174     175         -1           toyota celica gt   diesel      turbo   
120     121          1          plymouth fury iii      gas        std   
145     146          0                  subaru r2      gas      turbo   
15       16          0                     bmw x4      gas        std   
112     113          0              peugeot 604sl   diesel      turbo   
182     183          2           vokswagen rabbit   diesel        std   
149     150          0                  subaru dl      gas      turbo   

    doornumber      carbody drivewheel enginelocation  wheelbase  ...  \
164        two    hatchback        rwd          front       94.5  ...   
26        four        sedan        fwd          front       93.7  ...   
188       four        sedan        fwd          front       97.3  ...   
142       four        sedan        fwd          front       97.2  ...   
165        two        sedan        rwd          front       94.5  ...   
186       four        sedan        fwd          front       97.3  ...   
82         two    hatchback        fwd          front       95.9  ...   
196       four        sedan        rwd          front      104.3  ...   
144       four        sedan        4wd          front       97.0  ...   
195       four        wagon        rwd          front      104.3  ...   
50         two    hatchback        fwd          front       93.1  ...   
42         two        sedan        fwd          front       96

In [48]:
df.sort_values(by="car_ID")

car_ID  symboling                   CarName fueltype aspiration  \
0         1          3        alfa-romero giulia      gas        std   
1         2          3       alfa-romero stelvio      gas        std   
2         3          1  alfa-romero Quadrifoglio      gas        std   
3         4          2               audi 100 ls      gas        std   
4         5          2                audi 100ls      gas        std   
..      ...        ...                       ...      ...        ...   
200     201         -1           volvo 145e (sw)      gas        std   
201     202         -1               volvo 144ea      gas      turbo   
202     203         -1               volvo 244dl      gas        std   
203     204         -1                 volvo 246   diesel      turbo   
204     205         -1               volvo 264gl      gas      turbo   

    doornumber      carbody drivewheel enginelocation  wheelbase  ...  \
0          two  convertible        rwd          front       88.6  ...   
1          two  convertible        rwd          front       88.6  ...   
2          two    hatchback        rwd          front       94.5  ...   
3         four        sedan        fwd          front       99.8  ...   
4         four        sedan        4wd          front       99.4  ...   
..         ...          ...        ...            ...        ...  ...   
200       four        sedan        rwd          front      109.1  ...   
201       four        sedan        rwd          front      109.1  ...   
202       four        sedan        rwd          front      109.1  ...   
203       four        sedan        rwd          front      109.1  ...   
204       four        sedan        rwd          front      109.1  ...   

     enginesize  fuelsystem  boreratio  stroke compressionratio horsepower  \
0           130        mpfi       3.47    2.68              9.0        111   
1           130        mpfi       3.47    2.68              9.0        111   
2           152        mpfi       2.68    3.47              9.0        154   
3           109        mpfi       3.19    3.40             10.0        102   
4           136        mpfi       3.19    3.40              8.0        115   
..          ...         ...        ...     ...              ...        ...   
200         141        mpfi       3.78    3.15              9.5        114   
201         141        mpfi       3.78    3.15              8.7        160   
202         173        mpfi       3.58    2.87              8.8        134   
203         145         idi       3.01    3.40             23.0        106   
204         141        mpfi       3.78    3.15              9.5        114   

     peakrpm citympg  highwaympg    price  
0       5000      21          27  13495.0  
1       5000      21          27  16500.0  
2       5000      19          26  16500.0  
3       5500      24          30  13950.0  
4       5500      18          22  17450.0  
..       ...     ...         ...      ...  
200     5400      23          28  16845.0  
201     5300      19          25  19045.0  
202     5500      18          23  21485.0  
203     4800      26          27  22470.0  
204     5400      19          25  22625.0  

[205 rows x 26 columns]

In [59]:
df.sort_values(by="car_ID").reset_index(drop="index")

car_ID  symboling                   CarName fueltype aspiration  \
0         1          3        alfa-romero giulia      gas        std   
1         2          3       alfa-romero stelvio      gas        std   
2         3          1  alfa-romero Quadrifoglio      gas        std   
3         4          2               audi 100 ls      gas        std   
4         5          2                audi 100ls      gas        std   
..      ...        ...                       ...      ...        ...   
200     201         -1           volvo 145e (sw)      gas        std   
201     202         -1               volvo 144ea      gas      turbo   
202     203         -1               volvo 244dl      gas        std   
203     204         -1                 volvo 246   diesel      turbo   
204     205         -1               volvo 264gl      gas      turbo   

    doornumber      carbody drivewheel enginelocation  wheelbase  ...  \
0          two  convertible        rwd          front       88.6  ...   
1          two  convertible        rwd          front       88.6  ...   
2          two    hatchback        rwd          front       94.5  ...   
3         four        sedan        fwd          front       99.8  ...   
4         four        sedan        4wd          front       99.4  ...   
..         ...          ...        ...            ...        ...  ...   
200       four        sedan        rwd          front      109.1  ...   
201       four        sedan        rwd          front      109.1  ...   
202       four        sedan        rwd          front      109.1  ...   
203       four        sedan        rwd          front      109.1  ...   
204       four        sedan        rwd          front      109.1  ...   

     enginesize  fuelsystem  boreratio  stroke compressionratio horsepower  \
0           130        mpfi       3.47    2.68              9.0        111   
1           130        mpfi       3.47    2.68              9.0        111   
2           152        mpfi       2.68    3.47              9.0        154   
3           109        mpfi       3.19    3.40             10.0        102   
4           136        mpfi       3.19    3.40              8.0        115   
..          ...         ...        ...     ...              ...        ...   
200         141        mpfi       3.78    3.15              9.5        114   
201         141        mpfi       3.78    3.15              8.7        160   
202         173        mpfi       3.58    2.87              8.8        134   
203         145         idi       3.01    3.40             23.0        106   
204         141        mpfi       3.78    3.15              9.5        114   

     peakrpm citympg  highwaympg    price  
0       5000      21          27  13495.0  
1       5000      21          27  16500.0  
2       5000      19          26  16500.0  
3       5500      24          30  13950.0  
4       5500      18          22  17450.0  
..       ...     ...         ...      ...  
200     5400      23          28  16845.0  
201     5300      19          25  19045.0  
202     5500      18          23  21485.0  
203     4800      26          27  22470.0  
204     5400      19          25  22625.0  

[205 rows x 26 columns]

In [61]:
df.sort_values(by="car_ID",ascending=False)

car_ID  symboling                   CarName fueltype aspiration  \
204     205         -1               volvo 264gl      gas      turbo   
203     204         -1                 volvo 246   diesel      turbo   
202     203         -1               volvo 244dl      gas        std   
201     202         -1               volvo 144ea      gas      turbo   
200     201         -1           volvo 145e (sw)      gas        std   
..      ...        ...                       ...      ...        ...   
4         5          2                audi 100ls      gas        std   
3         4          2               audi 100 ls      gas        std   
2         3          1  alfa-romero Quadrifoglio      gas        std   
1         2          3       alfa-romero stelvio      gas        std   
0         1          3        alfa-romero giulia      gas        std   

    doornumber      carbody drivewheel enginelocation  wheelbase  ...  \
204       four        sedan        rwd          front      109.1  ...   
203       four        sedan        rwd          front      109.1  ...   
202       four        sedan        rwd          front      109.1  ...   
201       four        sedan        rwd          front      109.1  ...   
200       four        sedan        rwd          front      109.1  ...   
..         ...          ...        ...            ...        ...  ...   
4         four        sedan        4wd          front       99.4  ...   
3         four        sedan        fwd          front       99.8  ...   
2          two    hatchback        rwd          front       94.5  ...   
1          two  convertible        rwd          front       88.6  ...   
0          two  convertible        rwd          front       88.6  ...   

     enginesize  fuelsystem  boreratio  stroke compressionratio horsepower  \
204         141        mpfi       3.78    3.15              9.5        114   
203         145         idi       3.01    3.40             23.0        106   
202         173        mpfi       3.58    2.87              8.8        134   
201         141        mpfi       3.78    3.15              8.7        160   
200         141        mpfi       3.78    3.15              9.5        114   
..          ...         ...        ...     ...              ...        ...   
4           136        mpfi       3.19    3.40              8.0        115   
3           109        mpfi       3.19    3.40             10.0        102   
2           152        mpfi       2.68    3.47              9.0        154   
1           130        mpfi       3.47    2.68              9.0        111   
0           130        mpfi       3.47    2.68              9.0        111   

     peakrpm citympg  highwaympg    price  
204     5400      19          25  22625.0  
203     4800      26          27  22470.0  
202     5500      18          23  21485.0  
201     5300      19          25  19045.0  
200     5400      23          28  16845.0  
..       ...     ...         ...      ...  
4       5500      18          22  17450.0  
3       5500      24          30  13950.0  
2       5000      19          26  16500.0  
1       5000      21          27  16500.0  
0       5000      21          27  13495.0  

[205 rows x 26 columns]

In [65]:
df.describe()

car_ID   symboling   wheelbase   carlength    carwidth   carheight  \
count  205.000000  205.000000  205.000000  205.000000  205.000000  205.000000   
mean   103.000000    0.834146   98.756585  174.049268   65.907805   53.724878   
std     59.322565    1.245307    6.021776   12.337289    2.145204    2.443522   
min      1.000000   -2.000000   86.600000  141.100000   60.300000   47.800000   
25%     52.000000    0.000000   94.500000  166.300000   64.100000   52.000000   
50%    103.000000    1.000000   97.000000  173.200000   65.500000   54.100000   
75%    154.000000    2.000000  102.400000  183.100000   66.900000   55.500000   
max    205.000000    3.000000  120.900000  208.100000   72.300000   59.800000   

        curbweight  enginesize   boreratio      stroke  compressionratio  \
count   205.000000  205.000000  205.000000  205.000000        205.000000   
mean   2555.565854  126.907317    3.329756    3.255415         10.142537   
std     520.680204   41.642693    0.270844    0.313597          3.972040   
min    1488.000000   61.000000    2.540000    2.070000          7.000000   
25%    2145.000000   97.000000    3.150000    3.110000          8.600000   
50%    2414.000000  120.000000    3.310000    3.290000          9.000000   
75%    2935.000000  141.000000    3.580000    3.410000          9.400000   
max    4066.000000  326.000000    3.940000    4.170000         23.000000   

       horsepower      peakrpm     citympg  highwaympg         price  
count  205.000000   205.000000  205.000000  205.000000    205.000000  
mean   104.117073  5125.121951   25.219512   30.751220  13276.710571  
std     39.544167   476.985643    6.542142    6.886443   7988.852332  
min     48.000000  4150.000000   13.000000   16.000000   5118.000000  
25%     70.000000  4800.000000   19.000000   25.000000   7788.000000  
50%     95.000000  5200.000000   24.000000   30.000000  10295.000000  
75%    116.000000  5500.000000   30.000000   34.000000  16503.000000  
max    288.000000  6600.000000   49.000000   54.000000  45400.000000

In [71]:
df.columns

Index(['car_ID', 'symboling', 'CarName', 'fueltype', 'aspiration',
       'doornumber', 'carbody', 'drivewheel', 'enginelocation', 'wheelbase',
       'carlength', 'carwidth', 'carheight', 'curbweight', 'enginetype',
       'cylindernumber', 'enginesize', 'fuelsystem', 'boreratio', 'stroke',
       'compressionratio', 'horsepower', 'peakrpm', 'citympg', 'highwaympg',
       'price'],
      dtype='object')

In [73]:
df.CarName

0            alfa-romero giulia
1           alfa-romero stelvio
2      alfa-romero Quadrifoglio
3                   audi 100 ls
4                    audi 100ls
                 ...           
200             volvo 145e (sw)
201                 volvo 144ea
202                 volvo 244dl
203                   volvo 246
204                 volvo 264gl
Name: CarName, Length: 205, dtype: object

In [75]:
df["CarName"]

0            alfa-romero giulia
1           alfa-romero stelvio
2      alfa-romero Quadrifoglio
3                   audi 100 ls
4                    audi 100ls
                 ...           
200             volvo 145e (sw)
201                 volvo 144ea
202                 volvo 244dl
203                   volvo 246
204                 volvo 264gl
Name: CarName, Length: 205, dtype: object

In [79]:
df.groupby("wheelbase")["curbweight"].mean()

wheelbase
86.6     1766.000000
88.4     1488.000000
88.6     2548.000000
89.5     2770.666667
91.3     3105.000000
93.0     2145.000000
93.1     1918.000000
93.3     2240.000000
93.7     1998.900000
94.3     2337.000000
94.5     2112.047619
95.1     2008.000000
95.3     2411.250000
95.7     2216.615385
95.9     2861.800000
96.0     2734.000000
96.1     2519.500000
96.3     2379.000000
96.5     2249.125000
96.6     3685.000000
96.9     2535.000000
97.0     2410.000000
97.2     2260.200000
97.3     2262.857143
98.4     2765.857143
98.8     2409.666667
99.1     2745.500000
99.2     3139.000000
99.4     2824.000000
99.5     3053.000000
99.8     2422.000000
100.4    2875.666667
101.2    2566.250000
102.0    3950.000000
102.4    2418.400000
102.7    2910.000000
102.9    2996.000000
103.3    2535.000000
103.5    3221.666667
104.3    3020.833333
104.5    3141.000000
104.9    2685.000000
105.8    2961.333333
106.7    3495.000000
107.9    3145.166667
108.0    3130.000000
109.1    3058.400000
110

In [4]:
 df.groupby('CarName').agg({
    'wheelbase':['mean','sum'],
    'curbweight':['min','max']
})

NameError: name 'df' is not defined

In [86]:
#pivot -> it is used for reshape data

In [90]:
df.pivot_table(index='CarName',columns='fueltype',values='price',aggfunc='mean')

fueltype                   diesel      gas
CarName                                   
Nissan versa                  NaN   5499.0
alfa-romero Quadrifoglio      NaN  16500.0
alfa-romero giulia            NaN  13495.0
alfa-romero stelvio           NaN  16500.0
audi 100 ls                   NaN  13950.0
...                           ...      ...
volvo 246                 22470.0      NaN
volvo 264gl                   NaN  20522.5
volvo diesel                  NaN  18950.0
vw dasher                     NaN  11595.0
vw rabbit                     NaN   9980.0

[147 rows x 2 columns]

In [91]:
#melt ->transform or unpivot a DataFrame

In [6]:

df.melt(id_vars='CarName',var_name='fueltype', value_name='price')



C:\Users\Welcome\AppData\Local\Temp\ipykernel_11920\1505970776.py:1: FutureWarning: This dataframe has a column name that matches the 'value_name' column name of the resulting Dataframe. In the future this will raise an error, please set the 'value_name' parameter of DataFrame.melt to a unique name.
  df.melt(id_vars='CarName',var_name='fueltype', value_name='price')


CarName fueltype    price
0           alfa-romero giulia   car_ID        1
1          alfa-romero stelvio   car_ID        2
2     alfa-romero Quadrifoglio   car_ID        3
3                  audi 100 ls   car_ID        4
4                   audi 100ls   car_ID        5
...                        ...      ...      ...
5120           volvo 145e (sw)    price  16845.0
5121               volvo 144ea    price  19045.0
5122               volvo 244dl    price  21485.0
5123                 volvo 246    price  22470.0
5124               volvo 264gl    price  22625.0

[5125 rows x 3 columns]

In [8]:
additional_data = {
    'CarName': ['Nissan versa', 'alfa-romero Quadrifoglio', 'audi 100 ls', 'volvo 246', 'vw rabbit'],
    'Manufacturer': ['Nissan', 'Alfa-Romeo', 'Audi', 'Volvo', 'VW'],
    'Year': [2015, 2016, 2017, 2018, 2019]
}

additional_df = pd.DataFrame(additional_data)
print("\nAdditional DataFrame:")
print(additional_df)



Additional DataFrame:
                    CarName Manufacturer  Year
0              Nissan versa       Nissan  2015
1  alfa-romero Quadrifoglio   Alfa-Romeo  2016
2               audi 100 ls         Audi  2017
3                 volvo 246        Volvo  2018
4                 vw rabbit           VW  2019


In [15]:
pd.merge(df, additional_df, on='CarName')



car_ID  symboling                   CarName fueltype aspiration doornumber  \
0       3          1  alfa-romero Quadrifoglio      gas        std        two   
1       4          2               audi 100 ls      gas        std       four   
2      90          1              Nissan versa      gas        std        two   
3     191          3                 vw rabbit      gas        std        two   
4     204         -1                 volvo 246   diesel      turbo       four   

     carbody drivewheel enginelocation  wheelbase  ...  boreratio  stroke  \
0  hatchback        rwd          front       94.5  ...       2.68    3.47   
1      sedan        fwd          front       99.8  ...       3.19    3.40   
2      sedan        fwd          front       94.5  ...       3.15    3.29   
3  hatchback        fwd          front       94.5  ...       3.19    3.40   
4      sedan        rwd          front      109.1  ...       3.01    3.40   

   compressionratio  horsepower peakrpm citympg  highwaympg    price  \
0               9.0         154    5000      19          26  16500.0   
1              10.0         102    5500      24          30  13950.0   
2               9.4          69    5200      31          37   5499.0   
3               8.5          90    5500      24          29   9980.0   
4              23.0         106    4800      26          27  22470.0   

   Manufacturer  Year  
0    Alfa-Romeo  2016  
1          Audi  2017  
2        Nissan  2015  
3            VW  2019  
4         Volvo  2018  

[5 rows x 28 columns]

In [4]:
import pandas as pd


data1 = {
    'CarName': ['Nissan versa', 'alfa-romero Quadrifoglio', 'alfa-romero giulia'],
    'price': [5499, 16500, 13495],
    'fueltype': ['gas', 'gas', 'gas']
}

df1 = pd.DataFrame(data1)
print("DataFrame 1:")
print(df1)


DataFrame 1:
                    CarName  price fueltype
0              Nissan versa   5499      gas
1  alfa-romero Quadrifoglio  16500      gas
2        alfa-romero giulia  13495      gas


In [6]:

data2 = {
    'CarName': ['alfa-romero stelvio', 'audi 100 ls', 'volvo 246'],
    'price': [16500, 13950, 22470],
    'fueltype': ['gas', 'gas', 'diesel']
}

df2 = pd.DataFrame(data2)
print("\nDataFrame 2:")
print(df2)



DataFrame 2:
               CarName  price fueltype
0  alfa-romero stelvio  16500      gas
1          audi 100 ls  13950      gas
2            volvo 246  22470   diesel


In [10]:
pd.concat([df1, df2], ignore_index=True)



CarName  price fueltype
0              Nissan versa   5499      gas
1  alfa-romero Quadrifoglio  16500      gas
2        alfa-romero giulia  13495      gas
3       alfa-romero stelvio  16500      gas
4               audi 100 ls  13950      gas
5                 volvo 246  22470   diesel

In [103]:

data3 = {
    'CarName': ['Nissan versa', 'alfa-romero Quadrifoglio', 'alfa-romero giulia'],
    'year': [2015, 2016, 2017],
    'Manufacturer': ['Nissan', 'Alfa-Romeo', 'Alfa-Romeo']
}

df3= pd.DataFrame(data3)
print("\nDataFrame 3:")
print(df3)

concatenated_df_horizontal = pd.concat([df1, df3], axis=1)

print("\nConcatenated DataFrame (horizontal):")
print(concatenated_df_horizontal)



DataFrame 3:
                    CarName  year Manufacturer
0              Nissan versa  2015       Nissan
1  alfa-romero Quadrifoglio  2016   Alfa-Romeo
2        alfa-romero giulia  2017   Alfa-Romeo

Concatenated DataFrame (horizontal):
                    CarName  price fueltype                   CarName  year  \
0              Nissan versa   5499      gas              Nissan versa  2015   
1  alfa-romero Quadrifoglio  16500      gas  alfa-romero Quadrifoglio  2016   
2        alfa-romero giulia  13495      gas        alfa-romero giulia  2017   

  Manufacturer  
0       Nissan  
1   Alfa-Romeo  
2   Alfa-Romeo  


In [27]:
df.drop('fueltype',axis=1)


KeyError: "['fueltype'] not found in axis"

In [ ]:
df

In [26]:
df

car_ID  symboling                   CarName aspiration doornumber  \
0         1          3        alfa-romero giulia        std        two   
1         2          3       alfa-romero stelvio        std        two   
2         3          1  alfa-romero Quadrifoglio        std        two   
3         4          2               audi 100 ls        std       four   
4         5          2                audi 100ls        std       four   
..      ...        ...                       ...        ...        ...   
200     201         -1           volvo 145e (sw)        std       four   
201     202         -1               volvo 144ea      turbo       four   
202     203         -1               volvo 244dl        std       four   
203     204         -1                 volvo 246      turbo       four   
204     205         -1               volvo 264gl      turbo       four   

         carbody drivewheel enginelocation  wheelbase  carlength  ...  \
0    convertible        rwd          front       88.6      168.8  ...   
1    convertible        rwd          front       88.6      168.8  ...   
2      hatchback        rwd          front       94.5      171.2  ...   
3          sedan        fwd          front       99.8      176.6  ...   
4          sedan        4wd          front       99.4      176.6  ...   
..           ...        ...            ...        ...        ...  ...   
200        sedan        rwd          front      109.1      188.8  ...   
201        sedan        rwd          front      109.1      188.8  ...   
202        sedan        rwd          front      109.1      188.8  ...   
203        sedan        rwd          front      109.1      188.8  ...   
204        sedan        rwd          front      109.1      188.8  ...   

     enginesize  fuelsystem  boreratio stroke compressionratio  horsepower  \
0           130        mpfi       3.47   2.68              9.0         111   
1           130        mpfi       3.47   2.68              9.0         111   
2           152        mpfi       2.68   3.47              9.0         154   
3           109        mpfi       3.19   3.40             10.0         102   
4           136        mpfi       3.19   3.40              8.0         115   
..          ...         ...        ...    ...              ...         ...   
200         141        mpfi       3.78   3.15              9.5         114   
201         141        mpfi       3.78   3.15              8.7         160   
202         173        mpfi       3.58   2.87              8.8         134   
203         145         idi       3.01   3.40             23.0         106   
204         141        mpfi       3.78   3.15              9.5         114   

    peakrpm  citympg  highwaympg    price  
0      5000       21          27  13495.0  
1      5000       21          27  16500.0  
2      5000       19          26  16500.0  
3      5500       24          30  13950.0  
4      5500       18          22  17450.0  
..      ...      ...         ...      ...  
200    5400       23          28  16845.0  
201    5300       19          25  19045.0  
202    5500       18          23  21485.0  
203    4800       26          27  22470.0  
204    5400       19          25  22625.0  

[205 rows x 25 columns]

In [32]:
df.rename(columns={"doornumber":"no_of_parts"})

    

car_ID  symboling                   CarName aspiration no_of_parts  \
0         1          3        alfa-romero giulia        std         two   
1         2          3       alfa-romero stelvio        std         two   
2         3          1  alfa-romero Quadrifoglio        std         two   
3         4          2               audi 100 ls        std        four   
4         5          2                audi 100ls        std        four   
..      ...        ...                       ...        ...         ...   
200     201         -1           volvo 145e (sw)        std        four   
201     202         -1               volvo 144ea      turbo        four   
202     203         -1               volvo 244dl        std        four   
203     204         -1                 volvo 246      turbo        four   
204     205         -1               volvo 264gl      turbo        four   

         carbody drivewheel enginelocation  wheelbase  carlength  ...  \
0    convertible        rwd          front       88.6      168.8  ...   
1    convertible        rwd          front       88.6      168.8  ...   
2      hatchback        rwd          front       94.5      171.2  ...   
3          sedan        fwd          front       99.8      176.6  ...   
4          sedan        4wd          front       99.4      176.6  ...   
..           ...        ...            ...        ...        ...  ...   
200        sedan        rwd          front      109.1      188.8  ...   
201        sedan        rwd          front      109.1      188.8  ...   
202        sedan        rwd          front      109.1      188.8  ...   
203        sedan        rwd          front      109.1      188.8  ...   
204        sedan        rwd          front      109.1      188.8  ...   

     enginesize  fuelsystem  boreratio stroke compressionratio  horsepower  \
0           130        mpfi       3.47   2.68              9.0         111   
1           130        mpfi       3.47   2.68              9.0         111   
2           152        mpfi       2.68   3.47              9.0         154   
3           109        mpfi       3.19   3.40             10.0         102   
4           136        mpfi       3.19   3.40              8.0         115   
..          ...         ...        ...    ...              ...         ...   
200         141        mpfi       3.78   3.15              9.5         114   
201         141        mpfi       3.78   3.15              8.7         160   
202         173        mpfi       3.58   2.87              8.8         134   
203         145         idi       3.01   3.40             23.0         106   
204         141        mpfi       3.78   3.15              9.5         114   

    peakrpm  citympg  highwaympg    price  
0      5000       21          27  13495.0  
1      5000       21          27  16500.0  
2      5000       19          26  16500.0  
3      5500       24          30  13950.0  
4      5500       18          22  17450.0  
..      ...      ...         ...      ...  
200    5400       23          28  16845.0  
201    5300       19          25  19045.0  
202    5500       18          23  21485.0  
203    4800       26          27  22470.0  
204    5400       19          25  22625.0  

[205 rows x 25 columns]

In [34]:
df.replace({'CarName':'alfa-romero giulia'},'Xylo')

car_ID  symboling                   CarName aspiration doornumber  \
0         1          3                      Xylo        std        two   
1         2          3       alfa-romero stelvio        std        two   
2         3          1  alfa-romero Quadrifoglio        std        two   
3         4          2               audi 100 ls        std       four   
4         5          2                audi 100ls        std       four   
..      ...        ...                       ...        ...        ...   
200     201         -1           volvo 145e (sw)        std       four   
201     202         -1               volvo 144ea      turbo       four   
202     203         -1               volvo 244dl        std       four   
203     204         -1                 volvo 246      turbo       four   
204     205         -1               volvo 264gl      turbo       four   

         carbody drivewheel enginelocation  wheelbase  carlength  ...  \
0    convertible        rwd          front       88.6      168.8  ...   
1    convertible        rwd          front       88.6      168.8  ...   
2      hatchback        rwd          front       94.5      171.2  ...   
3          sedan        fwd          front       99.8      176.6  ...   
4          sedan        4wd          front       99.4      176.6  ...   
..           ...        ...            ...        ...        ...  ...   
200        sedan        rwd          front      109.1      188.8  ...   
201        sedan        rwd          front      109.1      188.8  ...   
202        sedan        rwd          front      109.1      188.8  ...   
203        sedan        rwd          front      109.1      188.8  ...   
204        sedan        rwd          front      109.1      188.8  ...   

     enginesize  fuelsystem  boreratio stroke compressionratio  horsepower  \
0           130        mpfi       3.47   2.68              9.0         111   
1           130        mpfi       3.47   2.68              9.0         111   
2           152        mpfi       2.68   3.47              9.0         154   
3           109        mpfi       3.19   3.40             10.0         102   
4           136        mpfi       3.19   3.40              8.0         115   
..          ...         ...        ...    ...              ...         ...   
200         141        mpfi       3.78   3.15              9.5         114   
201         141        mpfi       3.78   3.15              8.7         160   
202         173        mpfi       3.58   2.87              8.8         134   
203         145         idi       3.01   3.40             23.0         106   
204         141        mpfi       3.78   3.15              9.5         114   

    peakrpm  citympg  highwaympg    price  
0      5000       21          27  13495.0  
1      5000       21          27  16500.0  
2      5000       19          26  16500.0  
3      5500       24          30  13950.0  
4      5500       18          22  17450.0  
..      ...      ...         ...      ...  
200    5400       23          28  16845.0  
201    5300       19          25  19045.0  
202    5500       18          23  21485.0  
203    4800       26          27  22470.0  
204    5400       19          25  22625.0  

[205 rows x 25 columns]

In [37]:
df.iloc[:, [1, 0]] = df[['car_ID', 'symboling']]

In [38]:
df[['car_ID', 'symboling']]

car_ID  symboling
0         1          1
1         2          2
2         3          3
3         4          4
4         5          5
..      ...        ...
200     201        201
201     202        202
202     203        203
203     204        204
204     205        205

[205 rows x 2 columns]

In [41]:
df.iloc[3] = {'aspiration': 9, 'doornumber': 99}


In [42]:
df

car_ID  symboling                   CarName aspiration doornumber  \
0       1.0        1.0        alfa-romero giulia        std        two   
1       2.0        2.0       alfa-romero stelvio        std        two   
2       3.0        3.0  alfa-romero Quadrifoglio        std        two   
3       NaN        NaN                       NaN        9.0       99.0   
4       NaN        NaN                       NaN        9.0       99.0   
..      ...        ...                       ...        ...        ...   
200   201.0      201.0           volvo 145e (sw)        std       four   
201   202.0      202.0               volvo 144ea      turbo       four   
202   203.0      203.0               volvo 244dl        std       four   
203   204.0      204.0                 volvo 246      turbo       four   
204   205.0      205.0               volvo 264gl      turbo       four   

         carbody drivewheel enginelocation  wheelbase  carlength  ...  \
0    convertible        rwd          front       88.6      168.8  ...   
1    convertible        rwd          front       88.6      168.8  ...   
2      hatchback        rwd          front       94.5      171.2  ...   
3            NaN        NaN            NaN        NaN        NaN  ...   
4            NaN        NaN            NaN        NaN        NaN  ...   
..           ...        ...            ...        ...        ...  ...   
200        sedan        rwd          front      109.1      188.8  ...   
201        sedan        rwd          front      109.1      188.8  ...   
202        sedan        rwd          front      109.1      188.8  ...   
203        sedan        rwd          front      109.1      188.8  ...   
204        sedan        rwd          front      109.1      188.8  ...   

     enginesize  fuelsystem  boreratio stroke compressionratio  horsepower  \
0         130.0        mpfi       3.47   2.68              9.0       111.0   
1         130.0        mpfi       3.47   2.68              9.0       111.0   
2         152.0        mpfi       2.68   3.47              9.0       154.0   
3           NaN         NaN        NaN    NaN              NaN         NaN   
4           NaN         NaN        NaN    NaN              NaN         NaN   
..          ...         ...        ...    ...              ...         ...   
200       141.0        mpfi       3.78   3.15              9.5       114.0   
201       141.0        mpfi       3.78   3.15              8.7       160.0   
202       173.0        mpfi       3.58   2.87              8.8       134.0   
203       145.0         idi       3.01   3.40             23.0       106.0   
204       141.0        mpfi       3.78   3.15              9.5       114.0   

    peakrpm  citympg  highwaympg    price  
0    5000.0     21.0        27.0  13495.0  
1    5000.0     21.0        27.0  16500.0  
2    5000.0     19.0        26.0  16500.0  
3       NaN      NaN         NaN      NaN  
4       NaN      NaN         NaN      NaN  
..      ...      ...         ...      ...  
200  5400.0     23.0        28.0  16845.0  
201  5300.0     19.0        25.0  19045.0  
202  5500.0     18.0        23.0  21485.0  
203  4800.0     26.0        27.0  22470.0  
204  5400.0     19.0        25.0  22625.0  

[205 rows x 25 columns]